/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drfma1;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author owner
 */
public class detect_fraud_rank extends javax.swing.JFrame {

    /**
     * Creates new form detect_fraud_rank
     */
    public detect_fraud_rank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Detect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try{
            File[] f2;
            System.out.println("hi");
File f1=new File("G:\\NetBeansProjects\\DRFMA1\\apk\\");
f2=f1.listFiles();
int k1=0;
for(File f3:f2)
{
    k1++;
     System.out.println("hi"+f3.getName());
}
int k2=1;
while(k2<=k1){
            Class.forName("oracle.jdbc.driver.OracleDriver");  
  
//step2 create  the connection object  

Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","laxmi");  
Statement stmt1=con.createStatement();  

 //step3 create the statement object  

ResultSet rs=stmt1.executeQuery("select * from rankuser where index1="+k2+"");
String[] uname=new String[1000];
int[] rank=new int[1000];
int[] index=new int[1000];
int i=0;
int j=0;
int m=0;
int flag=0;
int[] no=new int[1000];
while(rs.next())
{
    flag=1;
    uname[i]=rs.getString(1);
    
    rank[i]=rs.getInt(2);
    
    index[i]=rs.getInt(3);
i++;
    // index[j]=rs.getInt(3);
    
} 
if(flag==1){
 System.out.println("hi "+k2);
            Class.forName("oracle.jdbc.driver.OracleDriver");  

 Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","laxmi");  
  Statement stmt2=con1.createStatement();  

 //step3 create the statement object  
ResultSet rs1=stmt2.executeQuery("select * from rankapps where index1="+k2+"");
int arank=0;
while(rs1.next())
{
    arank=rs1.getInt(2);
    System.out.println("hi "+arank);

}
i=0;
String[] fraud=new String[1000];
m=0;
j=0;
while(rank[i]>0)
{
    System.out.println("hi "+arank);

    if(arank>rank[i])
    { 
        System.out.println("hi "+rank[i]+" "+arank);

        if( rank[i]<(arank-2))
        {
            m=0;
            int sum=0;
            while(m<i)
            {
                sum=sum+rank[m];
                m++;
            }
            int avg=0;
            avg=sum/i+1;
            if(avg>rank[i]){
            fraud[j]=uname[i];
            System.out.println(fraud[j]);
            j++;
            }
        }
    } 
    i++;
}
}
k2++;
}
        }
        catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detect_fraud_rank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detect_fraud_rank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detect_fraud_rank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detect_fraud_rank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detect_fraud_rank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
